/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jnu.h"
/* Header for class jwinbmp */

#ifndef _Included_jwinbmp
#define _Included_jwinbmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jwinbmp
 * Method:    resize
 * Signature: (Ljava/awt/image/BufferedImage;II)Ljava/awt/image/BufferedImage;
 */
JNIEXPORT jobject JNICALL Java_jwinbmp_resize
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
